"""remove metabolite options from run

Revision ID: 185259a481ee
Revises: 14322145f9b5
Create Date: 2014-01-29 17:55:26.581463

"""

# revision identifiers, used by Alembic.
revision = '185259a481ee'
down_revision = '14322145f9b5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        # sqlite can't drop columns so leave them in
#         op.drop_column(u'run', 'n_reaction_steps')
#         op.drop_column(u'run', 'metabolism_types')
        pass
    except OperationalError as e:
        print e
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'run', sa.Column('n_reaction_steps', sa.Integer(), nullable=True))
    op.add_column(u'run', sa.Column('metabolism_types', sa.Unicode(), nullable=True))
    ### end Alembic commands ###
