"""Added reactions

Revision ID: 28182dc2d089
Revises: None
Create Date: 2014-01-03 10:06:20.172703

"""

# revision identifiers, used by Alembic.
revision = '28182dc2d089'
down_revision = '4e953e8c6a7e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('reactions',
        sa.Column('reactid', sa.Integer(), nullable=False),
        sa.Column('reactant', sa.Integer(), nullable=True),
        sa.Column('product', sa.Integer(), nullable=True),
        sa.Column('name', sa.Unicode(), nullable=True),
        sa.ForeignKeyConstraint(['product'], ['metabolites.metid'], ),
        sa.ForeignKeyConstraint(['reactant'], ['metabolites.metid'], ),
        sa.PrimaryKeyConstraint('reactid')
        )
    except OperationalError as e:
        print e
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    ### end Alembic commands ###
