"""Added natoms

Revision ID: 4e953e8c6a7e
Revises: None
Create Date: 2014-01-03 10:08:37.098120

"""

# revision identifiers, used by Alembic.
revision = '4e953e8c6a7e'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column(u'metabolites', sa.Column('natoms', sa.Integer(), nullable=True))
        op.add_column(u'run', sa.Column('max_water_losses', sa.Integer(), nullable=True))
    except OperationalError as e:
        print e
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'run', 'max_water_losses')
    op.drop_column(u'metabolites', 'natoms')
    ### end Alembic commands ###
