language: python
python:
  - 2.7
  - 3.5
before_install:
  - if [ $TRAVIS_PYTHON_VERSION = 2.7 ]; then wget -nc http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ $TRAVIS_PYTHON_VERSION = 3.5 ]; then wget -nc http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p conda
  - source conda/bin/activate root
  - conda update --yes -q conda
  - conda install --yes -c rdkit rdkit
  - conda install --yes numpy cython lxml nose coverage setuptools pip
  - pip install zope.interface py-bcrypt
  - if [ $TRAVIS_PYTHON_VERSION = 2.7 ]; then pip install http://www.parallelpython.com/downloads/pp/pp-1.6.4.zip; fi
  - if [ $TRAVIS_PYTHON_VERSION = 3.5 ]; then pip install http://www.parallelpython.com/downloads/pp/pp-1.6.4.4.zip; fi
  - cd conda && wget -nc http://cdn.sencha.com/ext/gpl/ext-4.2.1-gpl.zip && cd .. && unzip -qnd web/magmaweb/static conda/ext-4.2.1-gpl.zip
  - nvm install 6.11.4
  - nvm use 6.11.4
install:
  - cd job && python setup.py develop && cd ..
  - python web/setup.py develop
  - cd web && npm install && cd ..
before_script:
  - npm install karma-cli
  - pip install nose 'coveralls<1.2'
  - cd job && echo -e '[magma job]\nstructure_database.online = False\nstructure_database.pubchem=magma/tests/HMDB_MAGMa_test.db\nstructure_database.pubchem_halo=magma/tests/HMDB_MAGMa_test.db' > magma_job.ini && cd ..
script:
  - cd job && nosetests && cd ..
  - cd web && nosetests && cd ..
  - cd web && export PHANTOMJS_BIN=$PWD/node_modules/phantomjs-prebuilt/bin/phantomjs && node_modules/karma/bin/karma start && cd ..
  - cp web/.coverage .coverage.web && cp job/.coverage .coverage.job && coverage combine && coveralls
# TODO add Javascript coverage from web/coverage/*/lcov.info
sudo: false
cache:
  - web/magmaweb/static/ext-4.2.1.883
  - conda
  - web/node_modules
